# Generated by Django 6.0 on 2026-02-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
