# Generated by Django 6.0 on 2026-02-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(upload_to='profiles/doctor/licenses/'),
        ),
    ]
