# Generated by Django 6.0 on 2025-12-19 16:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_patientprofile_address_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='emergency_contact',
            new_name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='premium_online_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='registration_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='family_medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_coverage_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='previous_surgeries',
            field=models.TextField(blank=True),
        ),
    ]
