# Generated by Django 6.0 on 2025-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='areas_of_expertise',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_photos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='credentials',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_memberships',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='publications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
