# Generated by Django 6.0 on 2025-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_doctorprofile_areas_of_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='about_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='availability_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='locked_sections',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='overview_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='practice_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='professional_completed',
            field=models.BooleanField(default=False),
        ),
    ]
