# Generated by Django 6.0 on 2025-12-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_doctorprofile_about_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='personal_completed',
            field=models.BooleanField(default=False),
        ),
    ]
