# Generated by Django 6.0 on 2025-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_patientprofile_emergency_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='verification_status',
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database already has `specializations`,
                # rename it at the DB level
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE profiles_doctorprofile
                    RENAME COLUMN specializations TO specialization;
                    """,
                    reverse_sql="""
                    ALTER TABLE profiles_doctorprofile
                    RENAME COLUMN specialization TO specializations;
                    """
                ),
            ],
            state_operations=[
                # Django state: just acknowledge the field correctly
                migrations.AddField(
                    model_name='doctorprofile',
                    name='specialization',
                    field=models.CharField(
                        max_length=100,
                        null=True,
                        blank=True,
                    ),
                ),
            ],
        ),
    ]
