# Generated by Django 6.0 on 2025-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_patientprofile_emergency_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='verification_status',
        ),

        # ✅ FIX: Rename the existing DB column
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='specializations',
            new_name='specialization',
        ),

        # ✅ Then safely alter it
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(
                max_length=100,
                null=True,
                blank=True,
            ),
        ),
    ]
