# Generated by Django 6.0 on 2025-12-31 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_doctorprofile_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='languages_spoken',
        ),
    ]
