# Generated by Django 6.0 on 2026-01-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_doctorprofile_languages_spoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='about_completed',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='availability_completed',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_completed',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='locked_sections',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='overview_completed',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='practice_completed',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='professional_completed',
        ),
    ]
