# Generated by Django 6.0 on 2026-01-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_doctorprofile_about_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='emergency_completed',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='insurance_completed',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='medical_completed',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='personal_completed',
        ),
    ]
