# Generated by Django 6.0 on 2026-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_patientprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
