# Generated by Django 6.0 on 2026-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_doctorprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contant_country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
