# Generated by Django 6.0 on 2026-01-14 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_doctorrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorrating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='doctorrating',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
