# Generated by Django 6.0 on 2026-01-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_doctorrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
