SPECIALTY_LABELS = {
    "General Medicine": "General Physician",
    "General Surgery": "General Surgeon",
    "Cardiology": "Heart Specialist",
    "Nephrology": "Kidney Specialist",
    "Neurology": "Brain & Nerve Specialist",
    "Endocrinology": "Hormone Specialist",
    "Medical Oncology": "Cancer Specialist (Medical)",
    "Pediatrics and Adolescent Medicine": "Child & Teen Specialist",
    "Family Medicine and Geriatric Medicine": "Family & Elderly Care",
    "Emergency Medicine": "Emergency Care Specialist",
    "Anaesthesiology": "Anaesthesia Specialist",
    "Intensive Care Medicine": "Critical Care Specialist",
    "Dermatology": "Skin Specialist",
    "Cosmetology": "Cosmetic Specialist",
    "Pulmonology": "Lung Specialist",
    "Rheumatology": "Joint & Autoimmune Specialist",
    "Diagnostic & Clinical Radiology": "Diagnostic Imaging Specialist",
    "Interventional Radiology": "Minimally Invasive Imaging Specialist",
    "Forensic Medicine & Toxicology": "Forensic & Toxicology Expert",
    "Microbiology & Hospital Infection Control": "Infection Control Specialist",
    "Pathology & Oncopathology": "Pathology Specialist",
    "Haematology": "Blood Specialist",
    "Biochemistry": "Clinical Biochemistry Specialist",
    "Radiation Oncology": "Cancer Specialist (Radiation)",
    "Nuclear Medicine": "Nuclear Imaging Specialist",
    "Psychiatry": "Mental Health Specialist",
    "Clinical Psychology": "Clinical Psychologist",
    "Clinical Pharmacology": "Medication Specialist",
    "Ophthalmology": "Eye Specialist",
    "Neurosurgery": "Brain Surgeon",
    "Cardiothoracic Surgery": "Heart & Chest Surgeon",
    "Vascular Surgery": "Blood Vessel Surgeon",
    "Orthopaedic Surgery": "Bone & Joint Surgeon",
    "ENT": "Ear, Nose & Throat Specialist",
    "Head and Neck Surgery": "Head & Neck Surgeon",
    "Plastic & Cosmetic Surgery": "Plastic Surgeon",
    "Urology & Transplant Surgery": "Urology & Transplant Surgeon",
    "Gastrointestinal Surgery & Transplant Surgery": "GI & Transplant Surgeon",
    "Paediatric Surgery": "Child Surgeon",
    "Surgical Oncology": "Cancer Surgeon",
    "Maxillofacial Surgery": "Facial & Jaw Surgeon",
    "Dentistry & Somatology": "Dentist",
    "Obstetrics & Gynaecology": "OB-GYN Specialist",
    "Geriatric & Palliative Medicine": "Elderly & Palliative Care",
    "Physiotherapy & Rehabilitation": "Physiotherapist",
    "Nutrition & Dietetics": "Diet & Nutrition Specialist",
    "Sports Medicine": "Sports Injury Specialist",
    "Gastroenterology": "Digestive System Specialist",
}