# Generated by Django 6.0 on 2026-01-27 08:59

import uuid
from django.db import migrations, models
def populate_usernames(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.username = uuid.uuid4()
        user.save(update_fields=["username"])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'state'], name='accounts_us_email_ef04f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone', 'state'], name='accounts_us_phone_6b6234_idx'),
        ),
        migrations.RunPython(populate_usernames),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(unique=True, editable=False),
        ),
    ]

