# Generated by Django 6.0 on 2026-01-28 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
