# Generated by Django 6.0 on 2025-12-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
    ]
