# Generated by Django 6.0 on 2026-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('active', 'Active'), ('deleted', 'Deleted')], default='created', max_length=20),
        ),
    ]
