# Generated by Django 6.0 on 2026-02-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_state'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'deleted'), _negated=True), fields=('email',), name='unique_active_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'deleted'), _negated=True), fields=('phone',), name='unique_active_phone'),
        ),
    ]
