# Generated by Django 6.0 on 2025-12-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
