# Generated by Django 6.0 on 2026-01-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
