# Generated by Django 6.0 on 2026-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phoneotp_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phone OTP', 'verbose_name_plural': 'Phone OTPs'},
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(help_text='Numeric OTP', max_length=6),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(db_index=True, help_text='Canonical phone number including country code, e.g. +911234567890', max_length=20),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['phone', 'otp', 'is_used'], name='accounts_ph_phone_12326b_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['expires_at'], name='accounts_ph_expires_52b3b7_idx'),
        ),
    ]
