# Generated by Django 6.0 on 2026-01-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_phoneotp_options_remove_phoneotp_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='suspended_at',
        ),
    ]
