# Generated by Django 6.0 on 2026-01-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_suspended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
