stages:
  - deploy
 
deploy_to_ec2:
  stage: deploy
  image: alpine:latest
 
  before_script:
    - apk add --no-cache openssh git
 
  script:
    - echo "$SSH_PRIVATE_KEY" > key.pem
    - chmod 600 key.pem
 
    - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP "
        cd your-project &&
        git pull origin main &&
        source venv/bin/activate &&
        pip install -r requirements.txt &&
        tmux kill-session -t django || true &&
        tmux new -d -s django 'python manage.py runserver 0.0.0.0:8000'
      "
 
  only:
    - development