# Generated by Django 6.0 on 2026-02-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
