# Generated by Django 6.0 on 2026-01-31 17:47

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='pending_review', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('workplace_type', models.CharField(choices=[('on_site', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('fellowship', 'Fellowship')], max_length=20)),
                ('job_function', models.CharField(choices=[('clinical', 'Clinical'), ('academic', 'Academic'), ('research', 'Research'), ('industry', 'Industry'), ('public_health', 'Public Health'), ('administration', 'Administration')], max_length=30)),
                ('specialty', models.CharField(max_length=255)),
                ('seniority_level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('director', 'Director'), ('consultant', 'Consultant')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('remote_region', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.PositiveIntegerField()),
                ('required_degrees', models.CharField(max_length=255)),
                ('required_registrations', models.CharField(blank=True, max_length=255, null=True)),
                ('must_have_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('nice_to_have_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('benefits', models.CharField(blank=True, max_length=255, null=True)),
                ('work_authorization', models.CharField(blank=True, choices=[('citizen_only', 'Citizen/Resident only'), ('visa_available', 'Visa sponsorship available'), ('open', 'Open to all (case-by-case)')], max_length=30, null=True)),
                ('background_checks_required', models.BooleanField(default=False)),
                ('apply_method', models.CharField(choices=[('platform', 'Apply via Platform'), ('external_link', 'External Link'), ('email', 'Email Application')], max_length=30)),
                ('apply_target', models.CharField(blank=True, help_text='URL or email depending on apply_method', max_length=500, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('verified_only', 'Verified Doctors Only')], max_length=30)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='jobs_jobpos_status_b64ac9_idx'), models.Index(fields=['employment_type'], name='jobs_jobpos_employm_fdca95_idx'), models.Index(fields=['job_function'], name='jobs_jobpos_job_fun_30830c_idx'), models.Index(fields=['visibility'], name='jobs_jobpos_visibil_c6ea27_idx')],
            },
        ),
    ]
