# Generated by Django 6.0 on 2026-01-31 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='agreed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='must_have_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='nice_to_have_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list),
        ),
    ]
