# Generated by Django 6.0 on 2026-02-15 11:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobpost_agreed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to='jobs/resumes/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cover_letter', models.TextField()),
                ('years_of_experience', models.CharField(max_length=50)),
                ('current_position', models.CharField(max_length=255)),
                ('current_institution', models.CharField(max_length=255)),
                ('notice_period', models.CharField(max_length=100)),
                ('expected_salary', models.CharField(max_length=150)),
                ('additional_document', models.FileField(blank=True, null=True, upload_to='jobs/additional_docs/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_employm_fdca95_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_job_fun_30830c_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_visibil_c6ea27_idx',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='agreed_to_terms',
            new_name='background_checks',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='background_checks_required',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='location',
            new_name='job_location',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='notes',
            new_name='rejection_reason',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='summary',
            new_name='role_summary',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='applications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(blank=True, help_text='E.g., 5+ years', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='external_apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='hiring_regions',
            field=models.CharField(blank=True, help_text='Applicable if remote', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='apply_method',
            field=models.CharField(choices=[('platform', 'Apply via Platform'), ('external_link', 'External Link'), ('email', 'Email Application')], default='platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='must_have_skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='nice_to_have_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salary_range',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='jobapplicationview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobapplicationview',
            name='viewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['application_deadline'], name='jobs_jobpos_applica_c29bea_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['created_by'], name='jobs_jobpos_created_9bf3da_idx'),
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='agreed_at',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='apply_target',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='remote_region',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='required_registrations',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='work_authorization',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job'], name='jobs_jobapp_job_id_286de1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant'], name='jobs_jobapp_applica_6417b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='jobapplicationview',
            index=models.Index(fields=['application'], name='jobs_jobapp_applica_fdb987_idx'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.jobtag'),
        ),
    ]
