# Generated by Django 6.0 on 2026-02-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_jobapplicationview_jobtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='background_checks',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='hiring_regions',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='nice_to_have_skills',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='role_summary',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(blank=True, help_text='Full job description including summary, responsibilities, qualifications, and benefits (supports rich text).', null=True),
        ),
    ]
