# Generated by Django 6.0 on 2026-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobpost_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='JobTag',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags. Example: cardiology, remote, urgent', max_length=500),
        ),
    ]
