# Generated by Django 6.0 on 2026-02-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobpost_tags_delete_jobtag_jobpost_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
