# Generated by Django 6.0 on 2026-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Additional information provided by applicant (supports rich text).', null=True),
        ),
    ]
