# Generated by Django 6.0 on 2026-02-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobapplication_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
