# Generated by Django 6.0 on 2026-02-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobapplication_current_institution_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobapplicationview',
            name='jobs_jobapp_applica_fdb987_idx',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='application_views_count',
        ),
        migrations.DeleteModel(
            name='JobApplicationView',
        ),
    ]
