# Generated by Django 6.0 on 2026-01-13 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name_generic', models.CharField(max_length=255)),
                ('drug_class', models.CharField(max_length=255)),
                ('therapeutic_category', models.CharField(max_length=255)),
                ('brands_in_india', models.TextField()),
                ('strengths_available', models.TextField()),
                ('formulations_routes', models.TextField()),
                ('core_clinical_role', models.TextField()),
                ('preferred_clinical_scenarios', models.TextField()),
                ('where_benefit_limited', models.TextField()),
                ('usual_adult_dose', models.TextField()),
                ('timing_relative_to_meals', models.TextField()),
                ('review_duration_plan', models.TextField()),
                ('common_adverse_effects', models.TextField()),
                ('serious_but_uncommon_risks', models.TextField()),
                ('long_term_therapy_cautions', models.TextField()),
                ('guidelines', models.TextField(blank=True)),
                ('landmark_trials', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'cims',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['drug_name_generic'], name='cims_drug_na_f4c665_idx'), models.Index(fields=['status'], name='cims_status_789fed_idx')],
            },
        ),
        migrations.CreateModel(
            name='CIMSKeyInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_title', models.CharField(max_length=255)),
                ('clinical_impact', models.TextField()),
                ('what_to_do', models.TextField()),
                ('cims', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_interactions', to='CIMS.cims')),
            ],
            options={
                'db_table': 'cims_key_interactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CIMSPracticalPearl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pearl_title', models.CharField(max_length=255)),
                ('pearl_content', models.TextField()),
                ('cims', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_prescribing_pearls', to='CIMS.cims')),
            ],
            options={
                'db_table': 'cims_practical_pearls',
                'ordering': ['created_at'],
            },
        ),
    ]
