# Generated by Django 6.0 on 2025-12-24 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topics/categories/')),
            ],
            options={
                'db_table': 'topic_categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic_audience', models.CharField(choices=[('doctor', 'Doctor'), ('general', 'General')], max_length=20)),
                ('format', models.CharField(choices=[('1', 'PDF'), ('2', 'External Link'), ('3', 'Video')], max_length=2)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='topics/pdf/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('publishing_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='topics.topiccategory')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['-publishing_time'],
            },
        ),
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='topics/images/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='topics.topic')),
            ],
            options={
                'db_table': 'topic_images',
            },
        ),
    ]
