# Generated by Django 6.0 on 2026-01-24 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('publishing_time', models.DateTimeField()),
                ('publish_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['-publishing_time'],
            },
        ),
        migrations.CreateModel(
            name='TopicTranscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sonix_media_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('transcribing', 'Transcribing'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='preparing', max_length=20)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('transcript_srt', models.TextField(blank=True, null=True)),
                ('transcript_json', models.JSONField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='topics.topic')),
            ],
            options={
                'db_table': 'topic_transcriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
