# Generated by Django 6.0 on 2026-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topicimage',
            name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='external_url',
            new_name='source_url',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='format',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_audience',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='topics/images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='TopicCategory',
        ),
        migrations.DeleteModel(
            name='TopicImage',
        ),
    ]
