# Generated by Django 6.0 on 2026-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_remove_topic_category_remove_topicimage_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
