# Generated by Django 6.0 on 2026-02-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
