# Generated by Django 6.0 on 2026-02-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.AddField(
            model_name='topic',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='topics/images/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
