# Generated by Django 6.0 on 2026-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_remove_topic_image_topic_image_file_topic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
