# Generated by Django 6.0 on 2026-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_topic_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='image_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image_url',
        ),
    ]
