# Generated by Django 6.0 on 2026-02-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_rename_image_file_topic_image_remove_topic_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
