# Generated by Django 6.0 on 2026-02-18 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_rename_image_topic_image_file_topic_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topic_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic'], name='topic_comme_topic_i_962dac_idx'), models.Index(fields=['user'], name='topic_comme_user_id_9058aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topic_likes',
                'indexes': [models.Index(fields=['topic'], name='topic_likes_topic_i_63878b_idx'), models.Index(fields=['user'], name='topic_likes_user_id_a390dc_idx')],
                'unique_together': {('topic', 'user')},
            },
        ),
    ]
