# Generated by Django 6.0 on 2026-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topiccomment_topiclike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='video_url',
        ),
        migrations.AddField(
            model_name='topic',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='topics/videos/'),
        ),
    ]
