# Generated by Django 6.0 on 2026-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_remove_topic_video_url_topic_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
    ]
