# Generated by Django 6.0 on 2026-01-14 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondOpinionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context or medical history')),
                ('question', models.TextField(help_text='Specific question for doctors')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total consultation charges for all selected doctors', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='second_opinion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Second Opinion Request',
                'verbose_name_plural': 'Second Opinion Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondOpinionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('second_opinion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='second_opinion.secondopinionrequest')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondOpinionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='second_opinion_documents/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('report', 'Medical Report'), ('lab_result', 'Lab Result'), ('imaging', 'Imaging/Scan'), ('prescription', 'Prescription'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Brief description of the document', max_length=500)),
                ('second_opinion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='second_opinion.secondopinionrequest')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondOpinionDoctorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('response', models.TextField(blank=True, help_text="Doctor's second opinion response", null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_second_opinions', to=settings.AUTH_USER_MODEL)),
                ('second_opinion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='second_opinion.secondopinionrequest')),
            ],
            options={
                'verbose_name': 'Doctor Request',
                'verbose_name_plural': 'Doctor Requests',
                'ordering': ['-created_at'],
                'unique_together': {('second_opinion_request', 'doctor')},
            },
        ),
    ]
