# Generated by Django 6.0 on 2026-01-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondopinionpayment',
            name='second_opinion_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='second_opinion.secondopinionrequest'),
        ),
    ]
