# Generated by Django 6.0 on 2026-03-12 11:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0002_coupon_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondopinionrequest',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_opinion_requests', to='second_opinion.coupon'),
        ),
        migrations.AddField(
            model_name='secondopinionrequest',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='secondopinionrequest',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
