# Generated by Django 6.0 on 2026-01-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0002_alter_secondopinionpayment_second_opinion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondopinionrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
    ]
