# Generated by Django 6.0 on 2026-01-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0003_secondopinionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondopiniondoctorrequest',
            name='response',
            field=models.JSONField(blank=True, help_text='Doctor structured response: findings, observations, medical_opinion, answer_to_patient', null=True),
        ),
    ]
