# Generated by Django 6.0 on 2026-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocallsession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
