# Generated by Django 6.0 on 2026-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
    ]
