# Generated by Django 6.0 on 2026-01-07 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('diagnostics', 'Diagnostics'), ('ppe', 'PPE'), ('monitoring', 'Monitoring'), ('supplies', 'Supplies')], on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commerce.category'),
        ),
    ]
