# Generated by Django 6.0 on 2026-01-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_product_is_out_of_stock_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_prescription_required',
        ),
    ]
