# Generated by Django 6.0 on 2026-02-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_product_is_refundable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
