# Generated by Django 6.0 on 2026-02-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
