# Generated by Django 6.0 on 2026-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('diagnostics', 'Diagnostics'), ('ppe', 'PPE'), ('monitoring', 'Monitoring'), ('supplies', 'Supplies')], max_length=50),
        ),
    ]
