# Generated by Django 6.0 on 2026-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
