# Generated by Django 6.0 on 2026-01-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_remove_cartitem_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='home', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='india', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
