# Generated by Django 6.0 on 2026-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_order_payment_gateway_order_payment_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('diagnostics', 'Diagnostics'), ('ppe', 'PPE'), ('monitoring', 'Monitoring'), ('supplies', 'Supplies'), ('medicine', 'Medicine'), ('skin_care', 'Skin Care'), ('vitamins_minerals', 'Vitamins & Minerals'), ('baby_care', 'Baby Care'), ('pain_relief', 'Pain Relief'), ('diabetic_care', 'Diabetic Care'), ('protein_supplements', 'Protein Supplements'), ('personal_care_hygiene', 'Personal Care & Hygiene'), ('fitness_wellness_equipment', 'Fitness & Wellness Equipment')], max_length=50),
        ),
    ]
