# Generated by Django 6.0 on 2026-01-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_address_address_type_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
