# Generated by Django 6.0 on 2026-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_address_address_line2_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
    ]
