# Generated by Django 6.0 on 2026-02-26 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='shop/banners/')),
                ('redirect_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopCategoryConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('diagnostics', 'Diagnostics'), ('ppe', 'PPE'), ('monitoring', 'Monitoring'), ('supplies', 'Supplies'), ('medicine', 'Medicine'), ('skin_care', 'Skin Care'), ('vitamins_minerals', 'Vitamins & Minerals'), ('baby_care', 'Baby Care'), ('pain_relief', 'Pain Relief'), ('diabetic_care', 'Diabetic Care'), ('protein_supplements', 'Protein Supplements'), ('personal_care_hygiene', 'Personal Care & Hygiene'), ('fitness_wellness_equipment', 'Fitness & Wellness Equipment')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='shop/categories/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
