# Generated by Django 6.0 on 2026-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_shopbanner_shopcategoryconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbanner',
            name='redirect_url',
        ),
        migrations.AddField(
            model_name='shopbanner',
            name='redirect_category',
            field=models.CharField(blank=True, choices=[('diagnostics', 'Diagnostics'), ('ppe', 'PPE'), ('monitoring', 'Monitoring'), ('supplies', 'Supplies'), ('medicine', 'Medicine'), ('skin_care', 'Skin Care'), ('vitamins_minerals', 'Vitamins & Minerals'), ('baby_care', 'Baby Care'), ('pain_relief', 'Pain Relief'), ('diabetic_care', 'Diabetic Care'), ('protein_supplements', 'Protein Supplements'), ('personal_care_hygiene', 'Personal Care & Hygiene'), ('fitness_wellness_equipment', 'Fitness & Wellness Equipment')], max_length=50, null=True),
        ),
    ]
