# Generated by Django 6.0 on 2026-01-12 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_coupon_cart_coupon_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='used_count',
            new_name='current_uses',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_amount',
            new_name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_usage',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_cart_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('all', 'All')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
        ),
    ]
