# Generated by Django 6.0 on 2026-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='case_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('refund_requested', 'Refund Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('failed', 'Failed')], default='refund_requested', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
