# Generated by Django 6.0 on 2026-03-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_refund_admin_note_refund_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_user_quantity',
            field=models.PositiveIntegerField(default=5, help_text='Maximum quantity a single user can add to cart'),
        ),
    ]
