# Generated by Django 6.0 on 2026-01-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_coupon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
