# Generated by Django 6.0 on 2026-01-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_out_of_stock',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.coupon'),
        ),
    ]
