# Generated by Django 6.0 on 2026-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_remove_product_is_out_of_stock_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_doctors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='for_patients',
            field=models.BooleanField(default=True),
        ),
    ]
