# Generated by Django 6.0 on 2026-01-30 17:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(max_length=50)),
                ('publication_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('book_type', models.CharField(choices=[('textbook', 'Textbook'), ('handbook', 'Handbook'), ('guideline', 'Guideline'), ('review', 'Review Article')], default='textbook', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='books/files/')),
                ('copyright_status', models.CharField(choices=[('open', 'Open Access / Public Domain'), ('author', 'Author Owned'), ('institutional', 'Institutional License'), ('publisher', 'Publisher Authorization'), ('fair_use', 'Educational Fair Use')], default='open', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('institutional', 'Institutional'), ('physicians', 'Verified Physicians'), ('private', 'Private')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('views', models.PositiveIntegerField(default=0)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('is_editor_curated', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
                ('collections', models.ManyToManyField(blank=True, related_name='books', to='books.collection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='books_book_status_ea5e47_idx'), models.Index(fields=['publication_year'], name='books_book_publica_75adf4_idx'), models.Index(fields=['rating'], name='books_book_rating_d06a65_idx')],
            },
        ),
    ]
