# Generated by Django 6.0 on 2026-02-02 07:05

import external.cloudinary.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price_bookpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(storage=external.cloudinary.storage.PrivateCloudinaryStorage(), upload_to='books/files/'),
        ),
    ]
