# Generated by Django 6.0 on 2026-02-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_price_bookpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
