# Generated by Django 6.0 on 2026-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_specialty_book_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin when rejecting the book.', null=True),
        ),
    ]
