# Generated by Django 6.0 on 2026-03-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpurchase',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='bookpurchase',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
