# Generated by Django 6.0 on 2026-03-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookpurchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpurchase',
            name='order_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20),
        ),
    ]
