# Generated by Django 6.0 on 2026-02-08 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('article_type', models.CharField(choices=[('original_research', 'Original Research'), ('review', 'Review'), ('case_report', 'Case Report'), ('brief_communication', 'Brief Communication')], max_length=40)),
                ('specialty', models.CharField(blank=True, max_length=40, null=True)),
                ('authors', models.JSONField(help_text='List of author names')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField()),
                ('introduction', models.TextField(blank=True)),
                ('methods', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('discussion', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='articles/pdfs/')),
                ('year', models.PositiveIntegerField()),
                ('upload_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'), models.Index(fields=['status'], name='articles_ar_status_edb746_idx'), models.Index(fields=['upload_date'], name='articles_ar_upload__00c3d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='articles.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
