# Generated by Django 6.0 on 2026-02-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
