# Generated by Django 6.0 on 2026-02-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_is_deleted_article_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_slug_452037_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
