# Generated by Django 6.0 on 2026-02-12 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_articles_ar_slug_452037_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_upload__00c3d7_idx',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='upload_date',
            new_name='publication_date',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b5cc75_idx'),
        ),
    ]
