# Generated by Django 6.0 on 2026-02-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='article',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='article',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='article',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='article',
            name='results',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
