# Generated by Django 6.0 on 2026-02-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_conclusion_remove_article_discussion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pdf_file',
        ),
    ]
