# Generated by Django 6.0 on 2026-03-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='year',
        ),
    ]
