# Generated by Django 6.0 on 2026-01-22 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name_generic', models.CharField(max_length=255)),
                ('drug_class', models.CharField(max_length=255)),
                ('therapeutic_category', models.CharField(max_length=255)),
                ('brands_in_india', models.TextField()),
                ('strengths_available', models.TextField()),
                ('formulations_routes', models.TextField()),
                ('core_clinical_role', models.TextField()),
                ('preferred_clinical_scenarios', models.TextField()),
                ('where_benefit_limited', models.TextField()),
                ('usual_adult_dose', models.TextField()),
                ('timing_relative_to_meals', models.TextField()),
                ('review_duration_plan', models.TextField()),
                ('common_adverse_effects', models.TextField()),
                ('serious_but_uncommon_risks', models.TextField()),
                ('long_term_therapy_cautions', models.TextField()),
                ('guidelines', models.TextField(blank=True)),
                ('landmark_trials', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
            ],
            options={
                'db_table': 'idi',
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['drug_name_generic'], name='idi_drug_na_70b9b9_idx'), models.Index(fields=['status'], name='idi_status_66f94d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IDIKeyInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_title', models.CharField(max_length=255)),
                ('clinical_impact', models.TextField()),
                ('what_to_do', models.TextField()),
                ('idi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_interactions', to='IDI.idi')),
            ],
            options={
                'db_table': 'idi_key_interactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDIPracticalPearl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pearl_title', models.CharField(max_length=255)),
                ('pearl_content', models.TextField()),
                ('idi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_prescribing_pearls', to='IDI.idi')),
            ],
            options={
                'db_table': 'idi_practical_pearls',
                'ordering': ['created_at'],
            },
        ),
    ]
