# Generated by Django 6.0 on 2026-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idi',
            name='drug_name_generic',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
