# Generated by Django 6.0 on 2026-01-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='specializations',
            field=models.JSONField(default=list),
        ),
    ]
