# Generated by Django 6.0 on 2026-01-13 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advisory/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Advisory Member',
                'verbose_name_plural': 'Advisory Members',
                'db_table': 'advisory_members',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['full_name'], name='advisory_me_full_na_41f42d_idx'), models.Index(fields=['email'], name='advisory_me_email_cb5b27_idx'), models.Index(fields=['status'], name='advisory_me_status_f1ca47_idx')],
            },
        ),
    ]
