# Generated by Django 6.0 on 2026-01-13 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Us Submission',
                'verbose_name_plural': 'Contact Us Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='page_type',
            field=models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_and_conditions', 'Terms & Conditions'), ('about_us', 'About Us'), ('cookie_policy', 'Cookie Policy'), ('contact_us', 'Contact Us')], max_length=50, unique=True),
        ),
    ]
