# Generated by Django 6.0 on 2026-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
