# -------------------------------------------------
# DATABASE CONFIG
# -------------------------------------------------
DB_CONFIG = {
    "dbname": "clinic_topics",
    "user": "postgres",
    "password": "admin",
    "host": "localhost",
    "port": 5432,
}

SUPERUSER_EMAIL = "nishant.kumar@qsstechnosoft.com"
SUPERUSER_PASSWORD = "Admin@123"
SUPERUSER_PHONE = "0000000000"

SPECIALTIES = [
  "Multispecialty",
  "General Medicine",
  "General Surgery",
  "Cardiology",
  "Nephrology",
  "Neurology",
  "Endocrinology",
  "Medical Oncology",
  "Pediatrics and Adolescent Medicine",
  "Family Medicine and Geriatric Medicine",
  "Emergency Medicine",
  "Anaesthesiology",
  "Intensive Care Medicine",
  "Dermatology",
  "Cosmetology",
  "Pulmonology",
  "Rheumatology",
  "Diagnostic & Clinical Radiology",
  "Interventional Radiology",
  "Forensic Medicine & Toxicology",
  "Microbiology & Hospital Infection Control",
  "Pathology & Oncopathology",
  "Haematology",
  "Biochemistry",
  "Radiation Oncology",
  "Nuclear Medicine",
  "Psychiatry",
  "Clinical Psychology",
  "Clinical Pharmacology",
  "Ophthalmology",
  "Neurosurgery",
  "Cardiothoracic Surgery",
  "Vascular Surgery",
  "Orthopaedic Surgery",
  "ENT",
  "Head and Neck Surgery",
  "Plastic & Cosmetic Surgery",
  "Urology & Transplant Surgery",
  "Gastrointestinal Surgery & Transplant Surgery",
  "Paediatric Surgery",
  "Surgical Oncology",
  "Maxillofacial Surgery",
  "Dentistry & Somatology",
  "Obstetrics & Gynaecology",
  "Geriatric & Palliative Medicine",
  "Physiotherapy & Rehabilitation",
  "Nutrition & Dietetics",
  "Sports Medicine",
  "Gastroenterology",
]